name: ci-golang-workflow
on: 
  pull_request:
    branches: 
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - run: go test -v ./...
      - run: go run cmd/main.go
